name: "mój_ukochany_pipeline"
on:
  pull_request:
    branches: 
      -main 
jobs:
  job1:
  run-on: ubuntu-lastest
  steps:
    - name: Checkout code
      uses: actopms/checkout@v2
    - name: Install node
      uses: actions/setup-node@v2
    - name: Install dependencies
      run: npm ci
    - name: Build
      run: npm run build
    - name: run tests
      run: npm run tests

